# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Gal Weizman
tagline:          'Blog'
description:      '<a href="https://github.com/weizman">Github</a> | <a href="https://twitter.com/weizmangal">Twitter</a> | <a href="https://www.linkedin.com/in/weizmangal/">Linkedin</a>'
url:              https://weizman.github.io/
baseurl:          /
about:            /page-about

paginate:         5000
